[package]
name = "sys-log"
authors = ["The Moturus Project Developers"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
moto-log = { path = "../../lib/moto-log" }
moto-ipc = "0.1.0"
moto-sys = "0.1.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = "fat"
strip = true
codegen-units = 1

