[package]
name = "sys-io"
authors = ["The Moturus Project Developers"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
spin = { path = "../../third_party/spin" }

moto-runtime = { path = "../../lib/moto-runtime", features = ["rt-api"] }
flatfs       = { path = "../../lib/flatfs"      }
moto-ipc     = { path = "../../lib/moto-ipc"    }
moto-sys     = { path = "../../lib/moto-sys"    }
moto-virtio  = { path = "../../lib/virtio"      }
srfs         = { path = "../../lib/srfs"        }
configparser = { version = "3.0.2", default_features = false }
ipnetwork = { version = "0.20.0", default_features = false }
# smoltcp = "0.9.1"
smoltcp = "0.11.0"

[patch.crates-io]
flatfs       = { path = "../../lib/flatfs"      }
moto-ipc     = { path = "../../lib/moto-ipc"    }
moto-sys     = { path = "../../lib/moto-sys"    }
moto-virtio  = { path = "../../lib/virtio"      }
srfs         = { path = "../../lib/srfs"        }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = "fat"
strip = true
codegen-units = 1

