[package]
name = "imager"
authors = ["The Moturus Project Developers"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
flatfs = { path = "../lib/flatfs" }
mbrman = "0.5.2"
srfs = { path = "../lib/srfs" }

