[package]
name = "httpd"
description = "A simple HTTPd serving static content.."
authors = ["The Moturus Project Developers"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
time = { version = "0.3.36", default-features = false, features = ["std"] }
tiny_http = "0.12.0"

[profile.release]
panic = "abort"
lto = "fat"
strip = true
codegen-units = 1
